language: go

go:
  - 1.6
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true
sudo: false

script:
  - go get -v ./...
  - go test ./...
  - go build -v

notifications:
  email: false
