language: go

go:
  - master

sudo: false

install:
  - go get github.com/ChimeraCoder/anaconda
  - go get github.com/tj/go-dropy
  - go get github.com/kardianos/osext
  - go get github.com/stretchr/testify/assert

script:
  - go test ./...
  - go build -v

notifications:
  email: false
